### ISSUE TITLE
plugin/kubernetes AXFR fails due to missing NS

### ISSUE THREAD

**Issue by Doooooo0o** [coredns/coredns#2997]
# CoreDNS Version
1.5.0

# Corefile
```yaml
apiVersion: v1
data:
  Corefile: |
    .:53 {
        log
        errors
        health
        kubernetes my_fqdn in-addr.arpa ip6.arpa {
          transfer to 192.168.0.2
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 192.168.0.2
        loop
        reload
        loadbalance
    }
```
# Bind9 output
```
general: error: zone my_fqdn/IN: has no NS records
xfer-in: error: transfer of 'my_fqdn/IN' from 192.168.0.200#53: failed while receiving responses: bad zone
xfer-in: info: transfer of 'my_fqdn/IN' from 192.168.0.200#53: Transfer status: bad zone
xfer-in: info: transfer of 'my_fqdn/IN' from 192.168.0.200#53: Transfer completed: 13 messages, 336 records, 25159 bytes, 0.006 secs (4193166 bytes/sec)
```

And indeed, when doing a `dig AXFR @my_coredns_instance`, I got the whole zone transfered **but** the NS record which is critical for bind (and imho to the RFC)

# Expected result

Receive a NS record as well as the rest of the considered zone

**Comment by Doooooo0o** [comment]
Related question: I saw that [TSIG seemed to be implemented](https://github.com/coredns/client/blob/master/vendor/github.com/miekg/dns/tsig.go), but its not yet documented. Is it ready for production?

**Comment by miekg** [comment]
Tsig here? No that's not implement or planned.

**Comment by Doooooo0o** [comment]
> Tsig here? No that's not implement or planned.

Is there an alternate (minimal) "security" mechanism to ensure that both leader and replicas are authenticated except `transfer to a_specific_ip_address`?

**Comment by miekg** [comment]
DNS is public data, so this is hardly a priority. Still should fix this bug though

**Comment by Doooooo0o** [comment]
> DNS is public data

🤔
i'm trying to send an AXFR from coreDNS to a private internal DNS (bind9), I don't see anything public in here, or I haven't properly understood what you meant there.

**Comment by miekg** [comment]
Fixed in https://github.com/coredns/coredns/pull/4069
(will go out with 1.8.0)

**Comment by petrkr** [comment]
after 1 year this seems to not be fixed. I am using version 1.8.4 but still have same issue with bind9

I also tried 1.8.0 which was mentioned as fixes this issue. Also I tried 1.8.3... 

```
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/transfer: Outgoing transfer of 14 records of zone "dev.k8s.test.com." to fd00::61:260:56ff:fe00:66 for 1628778766 SOA serial
```


```
named[103476]: zone dev.k8s.test.com/IN: has no NS records
named[103476]: transfer of 'dev.k8s.test.com/IN' from fd00::c85:deb:f:51:3a#53: failed while receiving responses: bad zone
named[103476]: transfer of 'dev.k8s.test.com/IN' from fd00::c85:deb:f:51:3a#53: Transfer status: bad zone

```

**Comment by miekg** [comment]
Pretty sure we have a test (although only a unit test) that verifies the NS
records are there.

**Comment by chrisohaver** [comment]
Fixed in #4696

**Comment by chrisohaver** [comment]
@petrkr, 

FWIW - #4069 never merged directly, it was rebased into a new PR, which unintentionally omitted this fix.

The same bug was re-discovered in #4689, and fixed the following day in #4696, which has not released yet.

**Comment by petrkr** [comment]
I see, so this issue (meaning github issue) was never merged, that is why it still does not work in 1.8.4 release.

Ok I will wait for 1.8.5 release to check it out. Do you have any roadmap when you will release it? My corporate rules disallow to use master/development branches as everything must be from release ones.

Thanks guys.

**Comment by petrkr** [comment]
I can confirm, transfer works on 1.8.6

```[INFO] plugin/transfer: Outgoing transfer of 26 records of zone "dev.k8s.example.org." to fd00:6:48:61:260:56ff:fe00:66 for 1637840973 SOA serial```

```
Nov 25 12:52:21 vm66 named[615619]: zone dev.k8s.example.org/IN: Transfer started.
Nov 25 12:52:21 vm66 named[615619]: transfer of 'dev.k8s.example.org/IN' from fd00:6:48:c85:deb:f:62:1c4#53: connected using fd00:6:48:61:260:56ff:fe00:66#48861
Nov 25 12:52:21 vm66 named[615619]: zone dev.k8s.example.org/IN: transferred serial 1637840973
Nov 25 12:52:21 vm66 named[615619]: transfer of 'dev.k8s.example.org/IN' from fd00:6:48:c85:deb:f:62:1c4#53: Transfer status: success
Nov 25 12:52:21 vm66 named[615619]: transfer of 'dev.k8s.example.org/IN' from fd00:6:48:c85:deb:f:62:1c4#53: Transfer completed: 1 messages, 26 records, 2299 bytes, 0.009 secs (255444 bytes/sec)
```

However I have to use "masters" direct POD IP address, Can not use 'service' IP as it will results transfer fail

```
Nov 25 12:51:39 vm66 named[615588]: transfer of 'dev.k8s.example.org/IN' from fd00:6:48:c85:5deb:beef:bee2:53#53: failed while receiving responses: REFUSED
```

that is little-bit bad since pod IP can change as pods will creates/deletes.
