### ISSUE TITLE
CNAME Not resolving

### ISSUE THREAD

**Issue by mileswilson** [coredns/coredns#417]
I have a problem getting the following CNAME to resolve correctly:

```$TTL 3600
@ IN     SOA    ns1.example.io. admin.example.io. (
				2016110721  ; Serial
				3H          ; refresh after 3 hours
				1H          ; retry after 1 hour
				1W          ; expire after 1 week
				1D )         ; minimum TTL of 1 day

	; Name Server
	IN	NS	ns1.example.io.	; CoreDNS

ns1			IN A		10.20.130.24

*.app.exampleio.				IN	A	10.20.131.243

master01.example.io.				IN	A	10.20.131.233
node01.example.io.				IN	A	10.20.131.243
postgres.example.io.				IN 	CNAME    alongrandomstring.eu-west-1.rds.amazonaws.com.
```

I can nslookup fine:
```
10.20.130.24 - [09/Nov/2016:16:04:16 +0000] "A IN postgres.example.io. udp false 512" NOERROR 123 155.855µs
Server:		10.20.130.24
Address:	10.20.130.24#53

postgres.example.io.	canonical name = alongrandomstring.eu-west-1.rds.amazonaws.com.
```

But I cannot ping:

`ping: unknown host postgres.example.io`

Names have been changed to protect the innocent. 

I have the following corefile:

```
.:53 {
	file /opt/coredns/example.io.zone example.io
        prometheus
 	proxy . 8.8.8.8
	errors stdout
	log   stdout
}
```

Any ideas? alongrandomstring.eu-west-1.rds.amazonaws.com resolves fine via ping from the command line.

**Comment by miekg** [comment]
It's the sorting of the answer. Can you show some dig output?

**Comment by mileswilson** [comment]
Sure thing:

```
$ dig postgres.example.io

; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> postgres.example.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8262
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;postgres.example.io.   IN  A

;; ANSWER SECTION:
postgres.example.io.    3600 IN CNAME   alongrandomstring.eu-west-1.rds.amazonaws.com.

;; Query time: 0 msec
;; SERVER: 10.20.130.24#53(10.20.130.24)
;; WHEN: Wed Nov 09 16:48:57 UTC 2016
;; MSG SIZE  rcvd: 134

```

```
; <<>> DiG 9.9.4-RedHat-9.9.4-29.el7_2.4 <<>> alongrandomstring.eu-west-1.rds.amazonaws.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21278
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;alongrandomstring.eu-west-1.rds.amazonaws.com. IN A

;; ANSWER SECTION:
alongrandomstring.eu-west-1.rds.amazonaws.com. 4 IN A 10.20.130.192

;; Query time: 27 msec
;; SERVER: 10.20.130.24#53(10.20.130.24)
;; WHEN: Wed Nov 09 16:49:55 UTC 2016
;; MSG SIZE  rcvd: 106
```

thanks!

**Comment by miekg** [comment]
Ah it is an out of zone cname, but with the file back end. Hmmm.
Interesting. The file back end is auth only at the moment, so it will not
resolve this. But you probably have coredns as a proxy, so client expect a
resolved name, which the file backend does not give you...

**Comment by mileswilson** [comment]
ok - so I've tried making coredns not a proxy, but it still returns a record for the CNAME, and ping still doesn't like that.

I'm assuming there isn't a work-around for this behaviour at the moment?

**Comment by miekg** [comment]
No, there is no code in the file middleware that resolves that cname. I'm
pondering what would best here... should file have proxy capabilities? A
separate middleware that does this? Is cname/dname the only corner case?

**Comment by miekg** [comment]
Actually to be fair the etcd middleware already does this.

**Comment by miekg** [comment]
#418 is an early, non finished attempt at getting upstream cname resolving into the _file_ and _auto_ middleware - not finsihed, but show the route I want to take here.

Feel free (if you know Go) to play/fix with it.

**Comment by miekg** [comment]
https://github.com/miekg/coredns/pull/418 should now be in a shape worth playing with.

**Comment by miekg** [comment]
@mileswilson is PR #418 working for you?

**Comment by miekg** [comment]
Fixed with merging #437
